### ISSUE TITLE
Merge drake_interface with master

### ISSUE THREAD

**Issue by TobiaMarcucci** [TobiaMarcucci/pympc#16]
Hey @rdeits ,

I was thinking that now it's time to merge the work I've done during the last month with master. I would also like to not overwrite some of the thing that are in the master branch at the moment, maybe I'll need them in the future. What's the best practice for doing this? I was thinking to generate a new branch from master, let's say pympc_alpha, and then just leave it there like the humanoids _2017 one. Is this a good practice or should I proceed in another way?

Thanks!

**Comment by rdeits** [comment]
Hey, sorry for the late response! Yeah, I think keeping around a branch for that version is totally reasonable. The only danger is if you forget the branch exists 😉
